module.exports = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "previousAdmin",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "AdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "beacon",
        type: "address",
      },
    ],
    name: "BeaconUpgraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "tatacuyOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalSamiPoints",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "samiPointsClaimed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "changeSamiPoints",
        type: "uint256",
      },
    ],
    name: "FinishTatacuyCampaign",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tatacuyUuid",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "pachaUuid",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "creationDate",
        type: "uint256",
      },
    ],
    name: "MintTatacuy",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "previousAdminRole",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "newAdminRole",
        type: "bytes32",
      },
    ],
    name: "RoleAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "bytes32", name: "role", type: "bytes32" },
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "RoleRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalFundsPcuyDeposited",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_prizePerWinnerPcuy",
        type: "uint256",
      },
    ],
    name: "TatacuyCampaignStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "hasWon", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "prizeWinner",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "likelihood",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "pachaUuid",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tatacuyUuid",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pachaOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "idFromFront",
        type: "uint256",
      },
    ],
    name: "TatacuyTryMyLuckResult",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "implementation",
        type: "address",
      },
    ],
    name: "Upgraded",
    type: "event",
  },
  {
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "GAME_MANAGER",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PAUSER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "RNG_GENERATOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UPGRADER_ROLE",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tatacuyUuid", type: "uint256" },
    ],
    name: "finishTatacuyCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_account", type: "address" },
      { internalType: "uint256[]", name: "_randomNumbers", type: "uint256[]" },
    ],
    name: "fulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getListOfTatacuyCampaigns",
    outputs: [
      {
        components: [
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "tatacuyUuid", type: "uint256" },
          { internalType: "uint256", name: "pachaUuid", type: "uint256" },
          { internalType: "uint256", name: "creationDate", type: "uint256" },
          {
            internalType: "uint256",
            name: "totalFundsPcuyDeposited",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ratePcuyToSamiPoints",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalFundsSamiPoints",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "prizePerWinnerSamiPoints",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalSamiPointsClaimed",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "campaignStartDate",
            type: "uint256",
          },
          { internalType: "uint256", name: "campaignEndDate", type: "uint256" },
          { internalType: "bool", name: "hasTatacuy", type: "bool" },
          { internalType: "bool", name: "isCampaignActive", type: "bool" },
        ],
        internalType: "struct Tatacuy.TatacuyInfo[]",
        name: "listActiveCampaigns",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "role", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tatacuyUuid", type: "uint256" },
    ],
    name: "getTatacuyWithUuid",
    outputs: [
      {
        components: [
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "tatacuyUuid", type: "uint256" },
          { internalType: "uint256", name: "pachaUuid", type: "uint256" },
          { internalType: "uint256", name: "creationDate", type: "uint256" },
          {
            internalType: "uint256",
            name: "totalFundsPcuyDeposited",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ratePcuyToSamiPoints",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalFundsSamiPoints",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "prizePerWinnerSamiPoints",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalSamiPointsClaimed",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "campaignStartDate",
            type: "uint256",
          },
          { internalType: "uint256", name: "campaignEndDate", type: "uint256" },
          { internalType: "bool", name: "hasTatacuy", type: "bool" },
          { internalType: "bool", name: "isCampaignActive", type: "bool" },
        ],
        internalType: "struct Tatacuy.TatacuyInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_randomNumberGeneratorAddress",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "randomNumberGenerator",
    outputs: [
      {
        internalType: "contract IRandomNumberGenerator",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_account", type: "address" },
      { internalType: "uint256", name: "_pachaUuid", type: "uint256" },
      { internalType: "uint256", name: "_tatacuyUuid", type: "uint256" },
      { internalType: "bytes", name: "", type: "bytes" },
    ],
    name: "registerTatacuy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "role", type: "bytes32" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_infoAddress", type: "address" },
    ],
    name: "setPachacuyInfoAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tatacuyUuid", type: "uint256" },
      {
        internalType: "uint256",
        name: "_totalFundsPcuyDeposited",
        type: "uint256",
      },
      { internalType: "uint256", name: "_prizePerWinnerPcuy", type: "uint256" },
    ],
    name: "startTatacuyCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_account", type: "address" },
      { internalType: "uint256", name: "_likelihood", type: "uint256" },
      { internalType: "uint256", name: "_idFromFront", type: "uint256" },
      { internalType: "uint256", name: "_tatacuyUuid", type: "uint256" },
    ],
    name: "tryMyLuckTatacuy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newImplementation", type: "address" },
    ],
    name: "upgradeTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "newImplementation", type: "address" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
